use serde::{Deserialize, Serialize};

use super::super::*;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum PlayClientbound {
    BundleDelimiter,
    AddEntity(AddEntity),
    EntityAnimation(EntityAnimation),
    AwardStats(AwardStats),
    BlockChangedAck(BlockChangedAck),
    BlockDestruction(BlockDestruction),
    BlockEntityData(BlockEntityData),
    BlockEvent(BlockEvent),
    BlockUpdate(BlockUpdate),
    BossEvent(BossEvent),
    ChangeDifficulty(ChangeDifficulty),
    ChunkBatchStart,
    ChunkBatchFinished { batch_size: i32 },
    ChunksBiomes(ChunksBiomes),
    ClearDialog,
    ClearTitles(ClearTitles),
    CommandSuggestions(CommandSuggestions),
    ContainerClose(ContainerClose),
    ContainerSetContent(ContainerSetContent),
    ContainerSetData(ContainerSetData),
    ContainerSetSlot(ContainerSetSlot),
    CookieRequest(CookieRequest),
    Cooldown(Cooldown),
    CustomChatCompletions(CustomChatCompletions),
    CustomPayload(CustomPayload),
    CustomReportDetails(CustomReportDetails),
    ServerLinks(ServerLinks),
    DamageEvent(DamageEvent),
    DebugBlockValue(DebugBlockValue),
    DebugChunkValue(DebugChunkValue),
    DebugEntityValue(DebugEntityValue),
    DebugEvent(DebugEvent),
    DebugSample(DebugSample),
    DeleteChat(DeleteChat),
    Disconnect(Disconnect),
    DisguisedChat(DisguisedChat),
    EntityEvent(EntityEvent),
    EntityPositionSync(EntityPositionSync),
    Explosion(Explosion),
    ForgetLevelChunk(ForgetLevelChunk),
    GameEvent(GameEvent),
    GameRuleValues(GameRuleValues),
    GameTestHighlightPos(GameTestHighlightPos),
    HurtAnimation(HurtAnimation),
    InitializeBorder(InitializeBorder),
    KeepAlive { id: i64 },
    LevelEvent(LevelEvent),
    LevelParticles(LevelParticles),
    Ping { id: i32 },
    Login(PlayLogin),
    LowDiskSpaceWarning,
    MapItemData(MapItemData),
    MerchantOffers(MerchantOffers),
    MountScreenOpen(MountScreenOpen),
    MoveEntity(EntityMove),
    MoveVehicle(MoveVehicle),
    OpenBook(OpenBook),
    OpenScreen(OpenScreen),
    OpenSignEditor(OpenSignEditor),
    PlaceGhostRecipe(PlaceGhostRecipe),
    PlayerPosition(PlayerPositionUpdate),
    PlayerChat(PlayerChat),
    PlayerAbilities(PlayerAbilities),
    PlayerCombatEnd(PlayerCombatEnd),
    PlayerCombatEnter,
    PlayerCombatKill(PlayerCombatKill),
    PlayerInfoRemove(PlayerInfoRemove),
    PlayerInfoUpdate(PlayerInfoUpdate),
    PlayerLookAt(PlayerLookAt),
    PongResponse(PongResponse),
    PlayerRotation(PlayerRotationUpdate),
    ProjectilePower(ProjectilePower),
    RecipeBookAdd(RecipeBookAdd),
    RecipeBookRemove(RecipeBookRemove),
    RecipeBookSettings(RecipeBookSettings),
    RemoveEntities(RemoveEntities),
    RemoveMobEffect(RemoveMobEffect),
    ResetScore(ResetScore),
    ResourcePackPop(ResourcePackPop),
    ResourcePackPush(ResourcePackPush),
    Respawn(Respawn),
    RotateHead(RotateHead),
    ServerData(ServerData),
    SetActionBarText(SetActionBarText),
    SetBorderCenter(SetBorderCenter),
    SetBorderLerpSize(SetBorderLerpSize),
    SetBorderSize(SetBorderSize),
    SetBorderWarningDelay(SetBorderWarningDelay),
    SetBorderWarningDistance(SetBorderWarningDistance),
    SetCamera(SetCamera),
    SetCursorItem(SetCursorItem),
    SetDefaultSpawnPosition(SetDefaultSpawnPosition),
    SetEntityData(SetEntityData),
    SetEntityLink(SetEntityLink),
    SetEntityMotion(SetEntityMotion),
    SetEquipment(SetEquipment),
    SetExperience(PlayerExperience),
    SetHealth(PlayerHealth),
    SetHeldSlot(SetHeldSlot),
    SetPassengers(SetPassengers),
    SetPlayerInventory(SetPlayerInventory),
    SectionBlocksUpdate(SectionBlocksUpdate),
    SelectAdvancementsTab(SelectAdvancementsTab),
    SetChunkCacheCenter(SetChunkCacheCenter),
    SetChunkCacheRadius(SetChunkCacheRadius),
    SetSimulationDistance(SetSimulationDistance),
    SetDisplayObjective(SetDisplayObjective),
    SetObjective(SetObjective),
    SetPlayerTeam(SetPlayerTeam),
    SetScore(SetScore),
    SetSubtitleText(SetSubtitleText),
    StartConfiguration,
    StoreCookie(StoreCookie),
    SetTime(PlayTime),
    SetTitleText(SetTitleText),
    SetTitlesAnimation(SetTitlesAnimation),
    ShowDialog(ShowDialog),
    SoundEntity(SoundEntityEvent),
    Sound(SoundEvent),
    SystemChat(SystemChat),
    TabList(TabList),
    TagQuery(TagQuery),
    TakeItemEntity(TakeItemEntity),
    TeleportEntity(TeleportEntity),
    TestInstanceBlockStatus(TestInstanceBlockStatus),
    TickingState(TickingState),
    TickingStep(TickingStep),
    Transfer(Transfer),
    StopSound(StopSound),
    UpdateTags(UpdateTags),
    Waypoint(TrackedWaypointPacket),
    UpdateAttributes(UpdateAttributes),
    UpdateMobEffect(UpdateMobEffect),
    LevelChunkWithLight(LevelChunkWithLight),
    LightUpdate(LightUpdate),
    Unknown { packet_id: i32, len: usize },
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AwardStats {
    pub stats: Vec<StatUpdate>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct StatUpdate {
    pub stat_type_id: i32,
    pub value_id: i32,
    pub amount: i32,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Disconnect {
    pub reason: String,
    pub raw_reason: Vec<u8>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PlayLogin {
    pub player_id: i32,
    pub hardcore: bool,
    pub levels: Vec<String>,
    pub max_players: i32,
    pub chunk_radius: i32,
    pub simulation_distance: i32,
    pub reduced_debug_info: bool,
    pub show_death_screen: bool,
    pub do_limited_crafting: bool,
    pub common_spawn_info: CommonPlayerSpawnInfo,
    pub enforces_secure_chat: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct CommonPlayerSpawnInfo {
    pub dimension_type_id: i32,
    pub dimension: String,
    pub seed: i64,
    pub game_type: i8,
    pub previous_game_type: i8,
    pub is_debug: bool,
    pub is_flat: bool,
    pub last_death_location: Option<GlobalPos>,
    pub portal_cooldown: i32,
    pub sea_level: i32,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct GlobalPos {
    pub dimension: String,
    pub pos: BlockPos,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Respawn {
    pub common_spawn_info: CommonPlayerSpawnInfo,
    pub data_to_keep: i8,
}
