use bbb_protocol::packets::{
    AddEntity, AwardStats, BlockChangedAck, BlockDestruction, BlockEntityData, BlockEvent,
    BlockUpdate, BossEvent, ChangeDifficulty, ChunksBiomes, ClearTitles, CommandSuggestions,
    Commands, ContainerClose, ContainerSetContent, ContainerSetData, ContainerSetSlot, Cooldown,
    CustomChatCompletions, CustomPayload, CustomReportDetails, DamageEvent, DebugBlockValue,
    DebugChunkValue, DebugEntityValue, DebugEvent, DebugSample, DeleteChat, DisguisedChat,
    EntityAnimation, EntityEvent, EntityMove, EntityPositionSync, Explosion, ForgetLevelChunk,
    GameEvent, GameRuleValues, GameTestHighlightPos, HurtAnimation, InitializeBorder,
    LevelChunkWithLight, LevelEvent, LevelParticles, LightUpdate, MapItemData, MerchantOffers,
    MountScreenOpen, MoveMinecartAlongTrack, MoveVehicle, OpenBook, OpenScreen, OpenSignEditor,
    PlaceGhostRecipe, PlayLogin, PlayTime, PlayerAbilities, PlayerChat, PlayerCombatEnd,
    PlayerCombatKill, PlayerExperience, PlayerHealth, PlayerInfoRemove, PlayerInfoUpdate,
    PlayerLookAt, PlayerPositionUpdate, PlayerRotationUpdate, PongResponse, ProjectilePower,
    RecipeBookAdd, RecipeBookRemove, RecipeBookSettings, RegistryData, RemoveEntities,
    RemoveMobEffect, ResetScore, ResourcePackPop, ResourcePackPush, ResourcePackResponseAction,
    Respawn, RotateHead, SectionBlocksUpdate, SelectAdvancementsTab, ServerData, ServerLinks,
    SetActionBarText, SetBorderCenter, SetBorderLerpSize, SetBorderSize, SetBorderWarningDelay,
    SetBorderWarningDistance, SetCamera, SetChunkCacheCenter, SetChunkCacheRadius, SetCursorItem,
    SetDefaultSpawnPosition, SetDisplayObjective, SetEntityData, SetEntityLink, SetEntityMotion,
    SetEquipment, SetHeldSlot, SetObjective, SetPassengers, SetPlayerInventory, SetPlayerTeam,
    SetScore, SetSimulationDistance, SetSubtitleText, SetTitleText, SetTitlesAnimation, ShowDialog,
    SoundEntityEvent, SoundEvent, StopSound, SystemChat, TabList, TagQuery, TakeItemEntity,
    TeleportEntity, TestInstanceBlockStatus, TickingState, TickingStep, TrackedWaypointPacket,
    Transfer, UpdateAdvancements, UpdateAttributes, UpdateEnabledFeatures, UpdateMobEffect,
    UpdateRecipes, UpdateTags,
};

use super::ConnectionState;

#[derive(Debug, Clone)]
pub enum NetEvent {
    Connected,
    Disconnected {
        reason: Option<String>,
    },
    StateChanged {
        state: ConnectionState,
    },
    CompressionSet {
        threshold: i32,
    },
    CookieRequest {
        key: String,
        response_payload_present: bool,
    },
    CustomChatCompletions(CustomChatCompletions),
    CustomPayload(CustomPayload),
    StoreCookie {
        key: String,
        payload_len: usize,
        stored_cookie_count: usize,
    },
    CustomReportDetails(CustomReportDetails),
    ServerLinks(ServerLinks),
    AwardStats(AwardStats),
    ResetChat,
    UpdateEnabledFeatures(UpdateEnabledFeatures),
    CodeOfConduct {
        text: String,
    },
    ClearDialog,
    ShowDialog(ShowDialog),
    Waypoint(TrackedWaypointPacket),
    LowDiskSpaceWarning,
    MapItemData(MapItemData),
    MountScreenOpen(MountScreenOpen),
    OpenBook(OpenBook),
    OpenSignEditor(OpenSignEditor),
    PlaceGhostRecipe(PlaceGhostRecipe),
    PongResponse(PongResponse),
    DebugBlockValue(DebugBlockValue),
    DebugChunkValue(DebugChunkValue),
    DebugEntityValue(DebugEntityValue),
    DebugEvent(DebugEvent),
    DebugSample(DebugSample),
    DeleteChat(DeleteChat),
    DisguisedChat(DisguisedChat),
    GameRuleValues(GameRuleValues),
    GameTestHighlightPos(GameTestHighlightPos),
    TestInstanceBlockStatus(TestInstanceBlockStatus),
    PacketSeen {
        state: ConnectionState,
        packet_id: i32,
        len: usize,
    },
    ContainerClose(ContainerClose),
    ContainerSetContent(ContainerSetContent),
    ContainerSetData(ContainerSetData),
    ContainerSetSlot(ContainerSetSlot),
    MerchantOffers(MerchantOffers),
    OpenScreen(OpenScreen),
    SetCursorItem(SetCursorItem),
    SetPlayerInventory(SetPlayerInventory),
    BlockDestruction(BlockDestruction),
    AddEntity(AddEntity),
    EntityAnimation(EntityAnimation),
    EntityEvent(EntityEvent),
    HurtAnimation(HurtAnimation),
    MoveEntity(EntityMove),
    MoveMinecartAlongTrack(MoveMinecartAlongTrack),
    MoveVehicle(MoveVehicle),
    EntityPositionSync(EntityPositionSync),
    Explosion(Explosion),
    RemoveEntities(RemoveEntities),
    RotateHead(RotateHead),
    SetEntityData(SetEntityData),
    SetEntityLink(SetEntityLink),
    SetEntityMotion(SetEntityMotion),
    SetEquipment(SetEquipment),
    TakeItemEntity(TakeItemEntity),
    SetPassengers(SetPassengers),
    UpdateAttributes(UpdateAttributes),
    TeleportEntity(TeleportEntity),
    RegistryData(RegistryData),
    UpdateTags(UpdateTags),
    Login(PlayLogin),
    Respawn(Respawn),
    PlayerCombatEnd(PlayerCombatEnd),
    PlayerCombatEnter,
    PlayerCombatKill(PlayerCombatKill),
    PlayerLookAt(PlayerLookAt),
    PlayerPosition(PlayerPositionUpdate),
    PlayerRotation(PlayerRotationUpdate),
    RecipeBookAdd(RecipeBookAdd),
    RecipeBookRemove(RecipeBookRemove),
    RecipeBookSettings(RecipeBookSettings),
    PlayerInfoUpdate(PlayerInfoUpdate),
    PlayerInfoRemove(PlayerInfoRemove),
    ServerData(ServerData),
    ResourcePackPush(ResourcePackPush),
    ResourcePackResponse {
        id: uuid::Uuid,
        action: ResourcePackResponseAction,
    },
    ResourcePackPop(ResourcePackPop),
    Cooldown(Cooldown),
    DamageEvent(DamageEvent),
    UpdateMobEffect(UpdateMobEffect),
    RemoveMobEffect(RemoveMobEffect),
    PlayerAbilities(PlayerAbilities),
    PlayerChat(PlayerChat),
    PlayerHealth(PlayerHealth),
    PlayerExperience(PlayerExperience),
    HeldSlot(SetHeldSlot),
    SetDefaultSpawnPosition(SetDefaultSpawnPosition),
    SetSimulationDistance(SetSimulationDistance),
    SystemChat(SystemChat),
    SetActionBarText(SetActionBarText),
    SetTitleText(SetTitleText),
    SetSubtitleText(SetSubtitleText),
    ClearTitles(ClearTitles),
    SetTitlesAnimation(SetTitlesAnimation),
    Sound(SoundEvent),
    SoundEntity(SoundEntityEvent),
    StopSound(StopSound),
    TickingState(TickingState),
    TickingStep(TickingStep),
    Transfer(Transfer),
    UpdateAdvancements(UpdateAdvancements),
    UpdateRecipes(UpdateRecipes),
    SetCamera(SetCamera),
    InitializeBorder(InitializeBorder),
    SetBorderCenter(SetBorderCenter),
    SetBorderLerpSize(SetBorderLerpSize),
    SetBorderSize(SetBorderSize),
    SetBorderWarningDelay(SetBorderWarningDelay),
    SetBorderWarningDistance(SetBorderWarningDistance),
    ResetScore(ResetScore),
    SetDisplayObjective(SetDisplayObjective),
    SetObjective(SetObjective),
    SetPlayerTeam(SetPlayerTeam),
    SetScore(SetScore),
    Commands(Commands),
    CommandSuggestions(CommandSuggestions),
    SelectAdvancementsTab(SelectAdvancementsTab),
    BossEvent(BossEvent),
    ChangeDifficulty(ChangeDifficulty),
    TabList(TabList),
    TagQuery(TagQuery),
    GameEvent(GameEvent),
    SetTime(PlayTime),
    BlockEntityData(BlockEntityData),
    BlockEvent(BlockEvent),
    LevelEvent(LevelEvent),
    LevelParticles(LevelParticles),
    BlockUpdate(BlockUpdate),
    SectionBlocksUpdate(SectionBlocksUpdate),
    SetChunkCacheCenter(SetChunkCacheCenter),
    SetChunkCacheRadius(SetChunkCacheRadius),
    ForgetLevelChunk(ForgetLevelChunk),
    LevelChunkWithLight(LevelChunkWithLight),
    LightUpdate(LightUpdate),
    ChunksBiomes(ChunksBiomes),
    BlockChangedAck(BlockChangedAck),
    ProjectilePower(ProjectilePower),
}
