mod audio;
mod chat;
mod combat;
mod command_suggestions;
mod debug_game;
mod debug_query;
mod effects;
mod features;
mod hud;
mod inventory;
mod local_player;
mod local_player_collision;
mod local_player_destroy;
mod local_player_fluid;
mod local_player_movement;
mod player_info;
mod scoreboard;
mod server_presentation;
pub(crate) mod state;
mod stats;
mod ui;
mod waypoints;
mod world_border;

pub(crate) use local_player_collision::block_collision_shape_is_full_block;
