/// Renderer-owned frame/draw counters.
///
/// This is the renderer's source-of-truth counter block, updated as frames are
/// rendered, terrain is uploaded, atlases reallocate, and particles tick. The
/// downstream control crate keeps its own snapshot-facing `RendererCounters`
/// mirror; the native runtime projects this struct's fields into that mirror at
/// the snapshot boundary (mirroring the `NetCounters` pattern). Keeping the
/// authoritative counters here lets `bbb-control` stay a purely derived view
/// without depending on the renderer (and pulling in wgpu).
#[derive(Debug, Clone, Default)]
pub struct RendererCounters {
    pub frame_index: u64,
    pub width: u32,
    pub height: u32,
    pub draw_calls: u64,
    pub opaque_draw_calls: u64,
    pub cutout_draw_calls: u64,
    pub translucent_draw_calls: u64,
    pub block_destroy_overlay_draw_calls: u64,
    pub sky_draw_calls: u64,
    pub particle_draw_calls: u64,
    pub weather_draw_calls: u64,
    pub item_entity_draw_calls: u64,
    pub selection_draw_calls: u64,
    pub chunk_border_draw_calls: u64,
    pub entity_scene_draw_calls: u64,
    pub entity_target_draw_calls: u64,
    pub chunk_border_boxes: usize,
    pub entity_scene_boxes: usize,
    pub item_entity_billboards: usize,
    pub hud_draw_calls: u64,
    pub pipeline_switches: u64,
    pub screenshots_written: u64,
    pub queued_sections: usize,
    pub meshed_sections: usize,
    pub uploaded_sections: usize,
    pub visible_sections: usize,
    pub upload_bytes: u64,
    pub resident_bytes: u64,
    pub atlas_pages: usize,
    pub atlas_reallocations: u64,
    pub atlas_width: u32,
    pub atlas_height: u32,
    pub hud_crosshair_width: u32,
    pub hud_crosshair_height: u32,
    pub terrain_vertices: usize,
    pub terrain_indices: usize,
    pub opaque_faces: usize,
    pub cutout_faces: usize,
    pub translucent_faces: usize,
    pub culled_faces: usize,
    pub particle_spawn_batches: u64,
    pub particle_spawn_commands: u64,
    pub particle_missing_definitions: u64,
    pub particle_missing_sprites: u64,
    pub particle_unknown_types: u64,
    pub last_particle_spawn_count: usize,
    pub pending_particle_spawns: usize,
    pub dropped_particle_spawns: u64,
    pub active_particle_instances: usize,
    pub last_particle_intake_count: usize,
    pub last_particle_tick_count: usize,
    pub last_particle_expired_count: usize,
    pub last_particle_active_drop_count: usize,
    pub last_particle_limited_drop_count: usize,
    pub particle_runtime_ticks: u64,
    pub particle_instances_created: u64,
    pub particle_instances_expired: u64,
    pub dropped_active_particle_instances: u64,
    pub dropped_limited_particle_instances: u64,
}
