use super::{PartPose, PART_POSE_ZERO};
use crate::entity_models::instances::EntityModelInstance;
use crate::entity_models::model::{EntityModel, ModelCube, ModelPart};

// Vanilla ghasts are an off-white floating jelly; the colored fallback paints every cube the
// same light grey-white.
pub(in crate::entity_models) const GHAST_WHITE: [f32; 4] = [0.91, 0.91, 0.91, 1.0];

pub(in crate::entity_models) const MODEL_LAYER_GHAST: &str = "minecraft:ghast#main";

/// The nine ghast tentacle lengths, generated by vanilla `GhastModel.createBodyLayer` from a
/// fixed-seed `RandomSource.createThreadLocalInstance(1660L)` (`random.nextInt(7) + 8`,
/// `SingleThreadedRandomSource` = the Java legacy LCG). Deterministic, so they are baked in.
pub(in crate::entity_models) const GHAST_TENTACLE_LENGTHS: [f32; 9] =
    [8.0, 13.0, 9.0, 11.0, 11.0, 10.0, 12.0, 9.0, 12.0];

/// The nine ghast tentacle root offsets `[xo, 24.6, yo]` from vanilla
/// `GhastModel.createBodyLayer`: `xo = ((i%3 - i/3%2 * 0.5 + 0.25) / 2 * 2 - 1) * 5`,
/// `yo = (i/3 / 2 * 2 - 1) * 5`.
pub(in crate::entity_models) const GHAST_TENTACLE_OFFSETS: [[f32; 3]; 9] = [
    [-3.75, 24.6, -5.0],
    [1.25, 24.6, -5.0],
    [6.25, 24.6, -5.0],
    [-6.25, 24.6, 0.0],
    [-1.25, 24.6, 0.0],
    [3.75, 24.6, 0.0],
    [-3.75, 24.6, 5.0],
    [1.25, 24.6, 5.0],
    [6.25, 24.6, 5.0],
];

/// Vanilla `GhastModel.createBodyLayer` body cube: a 16×16×16 box at `texOffs(0, 0)`. The unified
/// cube carries the colored tint (`GHAST_WHITE`) and the textured `uv_size`/`texOffs` in one struct.
pub(in crate::entity_models) const GHAST_BODY_CUBE: [ModelCube; 1] = [ModelCube::new(
    [-8.0, -8.0, -8.0],
    [16.0, 16.0, 16.0],
    GHAST_WHITE,
    [16.0, 16.0, 16.0],
    [0.0, 0.0],
    false,
)];

/// The ghast body pose: `PartPose.offset(0, 17.6, 0)`.
pub(in crate::entity_models) const GHAST_BODY_POSE: PartPose = PartPose {
    offset: [0.0, 17.6, 0.0],
    rotation: [0.0, 0.0, 0.0],
};

/// Vanilla `GhastModel.createBodyLayer` tentacle child names, in `tentacle0..tentacle8` order;
/// `child_mut` needs `&'static` names, so the procedural ring draws its names from this const array.
const GHAST_TENTACLE_NAMES: [&str; 9] = [
    "tentacle0",
    "tentacle1",
    "tentacle2",
    "tentacle3",
    "tentacle4",
    "tentacle5",
    "tentacle6",
    "tentacle7",
    "tentacle8",
];

/// Bind cube of tentacle `i`: vanilla `addBox(-1, 0, -1, 2, len, 2)` at `texOffs(0, 0)` (reused for
/// the body and every tentacle, so each samples the same top-left region of the 64×32 texture). The
/// length comes from [`GHAST_TENTACLE_LENGTHS`]; `uv_size == size` (no deformation).
pub(in crate::entity_models) fn ghast_tentacle_cube(index: usize) -> ModelCube {
    let len = GHAST_TENTACLE_LENGTHS[index];
    ModelCube::new(
        [-1.0, 0.0, -1.0],
        [2.0, len, 2.0],
        GHAST_WHITE,
        [2.0, len, 2.0],
        [0.0, 0.0],
        false,
    )
}

/// Bind pose of tentacle `i`: vanilla `GhastModel.createBodyLayer` hangs it at
/// [`GHAST_TENTACLE_OFFSETS`]`[i]` (`y = 24.6`) with no rotation. The `xRot` wave is `0.4` at age 0
/// and overwritten each frame by `setup_anim`.
pub(in crate::entity_models) fn ghast_tentacle_pose(index: usize) -> PartPose {
    PartPose {
        offset: GHAST_TENTACLE_OFFSETS[index],
        rotation: [0.0, 0.0, 0.0],
    }
}

/// Vanilla `GhastModel.animateTentacles`: each tentacle's `xRot = 0.2 * sin(ageInTicks * 0.3
/// + i) + 0.4`, driven purely by `ageInTicks` (never at rest), so the tentacles always wave.
pub(in crate::entity_models) fn ghast_tentacle_x_rot(index: usize, age_in_ticks: f32) -> f32 {
    0.2 * (age_in_ticks * 0.3 + index as f32).sin() + 0.4
}

/// Mutable ghast model, mirroring vanilla `GhastModel`. The unified tree is built once with named
/// children: `body` plus `tentacle0..tentacle8`. `setup_anim` waves every tentacle's `xRot` from
/// `ageInTicks` ([`ghast_tentacle_x_rot`], never at rest). A ghast floats, so there is no walk swing
/// or head look; the bob/scale lives in the root transform (`ghast_model_root_transform`).
pub(in crate::entity_models) struct GhastModel {
    root: ModelPart,
}

impl GhastModel {
    pub(in crate::entity_models) fn new() -> Self {
        let mut children: Vec<(&'static str, ModelPart)> = Vec::with_capacity(10);
        children.push((
            "body",
            ModelPart::leaf(GHAST_BODY_POSE, GHAST_BODY_CUBE.to_vec()),
        ));
        for (i, &name) in GHAST_TENTACLE_NAMES.iter().enumerate() {
            children.push((
                name,
                ModelPart::leaf(ghast_tentacle_pose(i), vec![ghast_tentacle_cube(i)]),
            ));
        }
        Self {
            root: ModelPart::new(PART_POSE_ZERO, Vec::new(), children),
        }
    }
}

impl EntityModel for GhastModel {
    fn root(&self) -> &ModelPart {
        &self.root
    }

    fn root_mut(&mut self) -> &mut ModelPart {
        &mut self.root
    }

    fn setup_anim(&mut self, instance: &EntityModelInstance) {
        let age_in_ticks = instance.render_state.age_in_ticks;
        for (i, &name) in GHAST_TENTACLE_NAMES.iter().enumerate() {
            self.root.child_mut(name).pose.rotation[0] = ghast_tentacle_x_rot(i, age_in_ticks);
        }
    }
}
