use super::{ModelCubeDesc, ModelPartDesc, PartPose, TexturedModelCubeDesc, TexturedModelPartDesc};

// Vanilla ghasts are an off-white floating jelly; the colored fallback paints every cube the
// same light grey-white.
pub(in crate::entity_models) const GHAST_WHITE: [f32; 4] = [0.91, 0.91, 0.91, 1.0];

pub(in crate::entity_models) const MODEL_LAYER_GHAST: &str = "minecraft:ghast#main";

/// The nine ghast tentacle lengths, generated by vanilla `GhastModel.createBodyLayer` from a
/// fixed-seed `RandomSource.createThreadLocalInstance(1660L)` (`random.nextInt(7) + 8`,
/// `SingleThreadedRandomSource` = the Java legacy LCG). Deterministic, so they are baked in.
pub(in crate::entity_models) const GHAST_TENTACLE_LENGTHS: [f32; 9] =
    [8.0, 13.0, 9.0, 11.0, 11.0, 10.0, 12.0, 9.0, 12.0];

/// The nine ghast tentacle root offsets `[xo, 24.6, yo]` from vanilla
/// `GhastModel.createBodyLayer`: `xo = ((i%3 - i/3%2 * 0.5 + 0.25) / 2 * 2 - 1) * 5`,
/// `yo = (i/3 / 2 * 2 - 1) * 5`.
pub(in crate::entity_models) const GHAST_TENTACLE_OFFSETS: [[f32; 3]; 9] = [
    [-3.75, 24.6, -5.0],
    [1.25, 24.6, -5.0],
    [6.25, 24.6, -5.0],
    [-6.25, 24.6, 0.0],
    [-1.25, 24.6, 0.0],
    [3.75, 24.6, 0.0],
    [-3.75, 24.6, 5.0],
    [1.25, 24.6, 5.0],
    [6.25, 24.6, 5.0],
];

pub(in crate::entity_models) const GHAST_BODY_CUBE: [ModelCubeDesc; 1] = [ModelCubeDesc {
    min: [-8.0, -8.0, -8.0],
    size: [16.0, 16.0, 16.0],
    color: GHAST_WHITE,
}];

const GHAST_TENTACLE_0: [ModelCubeDesc; 1] = [ghast_tentacle_cube(0)];
const GHAST_TENTACLE_1: [ModelCubeDesc; 1] = [ghast_tentacle_cube(1)];
const GHAST_TENTACLE_2: [ModelCubeDesc; 1] = [ghast_tentacle_cube(2)];
const GHAST_TENTACLE_3: [ModelCubeDesc; 1] = [ghast_tentacle_cube(3)];
const GHAST_TENTACLE_4: [ModelCubeDesc; 1] = [ghast_tentacle_cube(4)];
const GHAST_TENTACLE_5: [ModelCubeDesc; 1] = [ghast_tentacle_cube(5)];
const GHAST_TENTACLE_6: [ModelCubeDesc; 1] = [ghast_tentacle_cube(6)];
const GHAST_TENTACLE_7: [ModelCubeDesc; 1] = [ghast_tentacle_cube(7)];
const GHAST_TENTACLE_8: [ModelCubeDesc; 1] = [ghast_tentacle_cube(8)];

const fn ghast_tentacle_cube(index: usize) -> ModelCubeDesc {
    ModelCubeDesc {
        min: [-1.0, 0.0, -1.0],
        size: [2.0, GHAST_TENTACLE_LENGTHS[index], 2.0],
        color: GHAST_WHITE,
    }
}

const fn ghast_tentacle_part(index: usize, cubes: &'static [ModelCubeDesc]) -> ModelPartDesc {
    ModelPartDesc {
        pose: PartPose {
            offset: GHAST_TENTACLE_OFFSETS[index],
            rotation: [0.0, 0.0, 0.0],
        },
        cubes,
        children: &[],
    }
}

// Vanilla 26.1 ModelLayers.GHAST: GhastModel.createBodyLayer(). The body sits at y 17.6 and
// the nine tentacles hang from y 24.6; the whole layer is scaled 4.5x by
// MeshTransformer.scaling at the model-root transform.
pub(in crate::entity_models) const GHAST_PARTS: [ModelPartDesc; 10] = [
    ModelPartDesc {
        pose: PartPose {
            offset: [0.0, 17.6, 0.0],
            rotation: [0.0, 0.0, 0.0],
        },
        cubes: &GHAST_BODY_CUBE,
        children: &[],
    },
    ghast_tentacle_part(0, &GHAST_TENTACLE_0),
    ghast_tentacle_part(1, &GHAST_TENTACLE_1),
    ghast_tentacle_part(2, &GHAST_TENTACLE_2),
    ghast_tentacle_part(3, &GHAST_TENTACLE_3),
    ghast_tentacle_part(4, &GHAST_TENTACLE_4),
    ghast_tentacle_part(5, &GHAST_TENTACLE_5),
    ghast_tentacle_part(6, &GHAST_TENTACLE_6),
    ghast_tentacle_part(7, &GHAST_TENTACLE_7),
    ghast_tentacle_part(8, &GHAST_TENTACLE_8),
];

pub(in crate::entity_models) const GHAST_TEXTURED_BODY_CUBE: [TexturedModelCubeDesc; 1] =
    [TexturedModelCubeDesc {
        min: [-8.0, -8.0, -8.0],
        size: [16.0, 16.0, 16.0],
        uv_size: [16.0, 16.0, 16.0],
        tex: [0.0, 0.0],
        mirror: false,
    }];

const GHAST_TEXTURED_TENTACLE_0: [TexturedModelCubeDesc; 1] = [ghast_textured_tentacle_cube(0)];
const GHAST_TEXTURED_TENTACLE_1: [TexturedModelCubeDesc; 1] = [ghast_textured_tentacle_cube(1)];
const GHAST_TEXTURED_TENTACLE_2: [TexturedModelCubeDesc; 1] = [ghast_textured_tentacle_cube(2)];
const GHAST_TEXTURED_TENTACLE_3: [TexturedModelCubeDesc; 1] = [ghast_textured_tentacle_cube(3)];
const GHAST_TEXTURED_TENTACLE_4: [TexturedModelCubeDesc; 1] = [ghast_textured_tentacle_cube(4)];
const GHAST_TEXTURED_TENTACLE_5: [TexturedModelCubeDesc; 1] = [ghast_textured_tentacle_cube(5)];
const GHAST_TEXTURED_TENTACLE_6: [TexturedModelCubeDesc; 1] = [ghast_textured_tentacle_cube(6)];
const GHAST_TEXTURED_TENTACLE_7: [TexturedModelCubeDesc; 1] = [ghast_textured_tentacle_cube(7)];
const GHAST_TEXTURED_TENTACLE_8: [TexturedModelCubeDesc; 1] = [ghast_textured_tentacle_cube(8)];

// Vanilla reuses `texOffs(0, 0)` for the body and every tentacle, so all of them sample the
// same top-left region of the 64x32 texture.
const fn ghast_textured_tentacle_cube(index: usize) -> TexturedModelCubeDesc {
    TexturedModelCubeDesc {
        min: [-1.0, 0.0, -1.0],
        size: [2.0, GHAST_TENTACLE_LENGTHS[index], 2.0],
        uv_size: [2.0, GHAST_TENTACLE_LENGTHS[index], 2.0],
        tex: [0.0, 0.0],
        mirror: false,
    }
}

const fn ghast_textured_tentacle_part(
    index: usize,
    cubes: &'static [TexturedModelCubeDesc],
) -> TexturedModelPartDesc {
    TexturedModelPartDesc {
        pose: PartPose {
            offset: GHAST_TENTACLE_OFFSETS[index],
            rotation: [0.0, 0.0, 0.0],
        },
        cubes,
        children: &[],
    }
}

pub(in crate::entity_models) const GHAST_TEXTURED_PARTS: [TexturedModelPartDesc; 10] = [
    TexturedModelPartDesc {
        pose: PartPose {
            offset: [0.0, 17.6, 0.0],
            rotation: [0.0, 0.0, 0.0],
        },
        cubes: &GHAST_TEXTURED_BODY_CUBE,
        children: &[],
    },
    ghast_textured_tentacle_part(0, &GHAST_TEXTURED_TENTACLE_0),
    ghast_textured_tentacle_part(1, &GHAST_TEXTURED_TENTACLE_1),
    ghast_textured_tentacle_part(2, &GHAST_TEXTURED_TENTACLE_2),
    ghast_textured_tentacle_part(3, &GHAST_TEXTURED_TENTACLE_3),
    ghast_textured_tentacle_part(4, &GHAST_TEXTURED_TENTACLE_4),
    ghast_textured_tentacle_part(5, &GHAST_TEXTURED_TENTACLE_5),
    ghast_textured_tentacle_part(6, &GHAST_TEXTURED_TENTACLE_6),
    ghast_textured_tentacle_part(7, &GHAST_TEXTURED_TENTACLE_7),
    ghast_textured_tentacle_part(8, &GHAST_TEXTURED_TENTACLE_8),
];

/// Vanilla `GhastModel.animateTentacles`: each tentacle's `xRot = 0.2 * sin(ageInTicks * 0.3
/// + i) + 0.4`, driven purely by `ageInTicks` (never at rest), so the tentacles always wave.
pub(in crate::entity_models) fn ghast_tentacle_x_rot(index: usize, age_in_ticks: f32) -> f32 {
    0.2 * (age_in_ticks * 0.3 + index as f32).sin() + 0.4
}
