pub mod handshake {
    pub const SERVERBOUND_CLIENT_INTENTION: i32 = 0x00;
}

pub mod status {
    pub const SERVERBOUND_STATUS_REQUEST: i32 = 0x00;
    pub const SERVERBOUND_PING_REQUEST: i32 = 0x01;

    pub const CLIENTBOUND_STATUS_RESPONSE: i32 = 0x00;
    pub const CLIENTBOUND_PONG_RESPONSE: i32 = 0x01;
}

pub mod login {
    pub const SERVERBOUND_HELLO: i32 = 0x00;
    pub const SERVERBOUND_KEY: i32 = 0x01;
    pub const SERVERBOUND_CUSTOM_QUERY_ANSWER: i32 = 0x02;
    pub const SERVERBOUND_LOGIN_ACKNOWLEDGED: i32 = 0x03;

    pub const CLIENTBOUND_LOGIN_DISCONNECT: i32 = 0x00;
    pub const CLIENTBOUND_HELLO: i32 = 0x01;
    pub const CLIENTBOUND_LOGIN_FINISHED: i32 = 0x02;
    pub const CLIENTBOUND_LOGIN_COMPRESSION: i32 = 0x03;
    pub const CLIENTBOUND_CUSTOM_QUERY: i32 = 0x04;
}

pub mod configuration {
    pub const SERVERBOUND_CLIENT_INFORMATION: i32 = 0x00;
    pub const SERVERBOUND_COOKIE_RESPONSE: i32 = 0x01;
    pub const SERVERBOUND_CUSTOM_PAYLOAD: i32 = 0x02;
    pub const SERVERBOUND_FINISH_CONFIGURATION: i32 = 0x03;
    pub const SERVERBOUND_KEEP_ALIVE: i32 = 0x04;
    pub const SERVERBOUND_PONG: i32 = 0x05;
    pub const SERVERBOUND_RESOURCE_PACK: i32 = 0x06;
    pub const SERVERBOUND_SELECT_KNOWN_PACKS: i32 = 0x07;

    pub const CLIENTBOUND_FINISH_CONFIGURATION: i32 = 0x03;
    pub const CLIENTBOUND_KEEP_ALIVE: i32 = 0x04;
    pub const CLIENTBOUND_PING: i32 = 0x05;
    pub const CLIENTBOUND_REGISTRY_DATA: i32 = 0x07;
    pub const CLIENTBOUND_SELECT_KNOWN_PACKS: i32 = 0x0e;
}

pub mod play {
    pub const CLIENTBOUND_ADD_ENTITY: i32 = 1;
    pub const CLIENTBOUND_BLOCK_CHANGED_ACK: i32 = 3;
    pub const CLIENTBOUND_BLOCK_UPDATE: i32 = 8;
    pub const CLIENTBOUND_CHUNK_BATCH_FINISHED: i32 = 11;
    pub const CLIENTBOUND_CHUNK_BATCH_START: i32 = 12;
    pub const CLIENTBOUND_CHUNKS_BIOMES: i32 = 13;
    pub const CLIENTBOUND_DISCONNECT: i32 = 32;
    pub const CLIENTBOUND_ENTITY_POSITION_SYNC: i32 = 35;
    pub const CLIENTBOUND_FORGET_LEVEL_CHUNK: i32 = 37;
    pub const CLIENTBOUND_GAME_EVENT: i32 = 38;
    pub const CLIENTBOUND_KEEP_ALIVE: i32 = 44;
    pub const CLIENTBOUND_LEVEL_CHUNK_WITH_LIGHT: i32 = 45;
    pub const CLIENTBOUND_LIGHT_UPDATE: i32 = 48;
    pub const CLIENTBOUND_LOGIN: i32 = 49;
    pub const CLIENTBOUND_MOVE_ENTITY_POS: i32 = 53;
    pub const CLIENTBOUND_MOVE_ENTITY_POS_ROT: i32 = 54;
    pub const CLIENTBOUND_MOVE_ENTITY_ROT: i32 = 56;
    pub const CLIENTBOUND_PING: i32 = 61;
    pub const CLIENTBOUND_PLAYER_ABILITIES: i32 = 64;
    pub const CLIENTBOUND_PLAYER_POSITION: i32 = 72;
    pub const CLIENTBOUND_REMOVE_ENTITIES: i32 = 77;
    pub const CLIENTBOUND_RESPAWN: i32 = 82;
    pub const CLIENTBOUND_ROTATE_HEAD: i32 = 83;
    pub const CLIENTBOUND_SECTION_BLOCKS_UPDATE: i32 = 84;
    pub const CLIENTBOUND_SET_CHUNK_CACHE_CENTER: i32 = 94;
    pub const CLIENTBOUND_SET_CHUNK_CACHE_RADIUS: i32 = 95;
    pub const CLIENTBOUND_SET_DEFAULT_SPAWN_POSITION: i32 = 97;
    pub const CLIENTBOUND_SET_ENTITY_DATA: i32 = 99;
    pub const CLIENTBOUND_SET_ENTITY_MOTION: i32 = 101;
    pub const CLIENTBOUND_SET_EXPERIENCE: i32 = 103;
    pub const CLIENTBOUND_SET_HEALTH: i32 = 104;
    pub const CLIENTBOUND_SET_HELD_SLOT: i32 = 105;
    pub const CLIENTBOUND_SET_SIMULATION_DISTANCE: i32 = 111;
    pub const CLIENTBOUND_SET_TIME: i32 = 113;
    pub const CLIENTBOUND_START_CONFIGURATION: i32 = 118;
    pub const CLIENTBOUND_SYSTEM_CHAT: i32 = 121;
    pub const CLIENTBOUND_TELEPORT_ENTITY: i32 = 125;

    pub const SERVERBOUND_ACCEPT_TELEPORTATION: i32 = 0;
    pub const SERVERBOUND_CHUNK_BATCH_RECEIVED: i32 = 11;
    pub const SERVERBOUND_CLIENT_COMMAND: i32 = 12;
    pub const SERVERBOUND_CLIENT_TICK_END: i32 = 13;
    pub const SERVERBOUND_CLIENT_INFORMATION: i32 = 14;
    pub const SERVERBOUND_CONFIGURATION_ACKNOWLEDGED: i32 = 16;
    pub const SERVERBOUND_KEEP_ALIVE: i32 = 28;
    pub const SERVERBOUND_MOVE_PLAYER_POS_ROT: i32 = 31;
    pub const SERVERBOUND_PICK_ITEM_FROM_BLOCK: i32 = 36;
    pub const SERVERBOUND_PLAYER_ACTION: i32 = 41;
    pub const SERVERBOUND_PLAYER_COMMAND: i32 = 42;
    pub const SERVERBOUND_PLAYER_INPUT: i32 = 43;
    pub const SERVERBOUND_PLAYER_LOADED: i32 = 44;
    pub const SERVERBOUND_PONG: i32 = 45;
    pub const SERVERBOUND_SET_CARRIED_ITEM: i32 = 53;
    pub const SERVERBOUND_SWING: i32 = 63;
    pub const SERVERBOUND_USE_ITEM_ON: i32 = 66;
    pub const SERVERBOUND_USE_ITEM: i32 = 67;
}
