use anyhow::{bail, Context, Result};
use bbb_pack::{PackRoots, ResourceLocation, SpriteImage};
use bbb_renderer::{entity_model_texture_refs, EntityModelTextureImage, EntityModelTextureRef};

pub(crate) fn load_entity_model_textures(
    renderer: &mut bbb_renderer::Renderer,
    roots: Option<&PackRoots>,
) {
    let Some(roots) = roots else {
        tracing::warn!(
            "continuing without vanilla entity textures because pack roots are unavailable"
        );
        return;
    };
    if let Err(err) = try_load_entity_model_textures(renderer, roots) {
        tracing::warn!(?err, "continuing without vanilla entity textures");
    }
}

fn try_load_entity_model_textures(
    renderer: &mut bbb_renderer::Renderer,
    roots: &PackRoots,
) -> Result<()> {
    let images = load_entity_model_texture_images(roots)?;
    renderer.upload_entity_model_textures(&images)?;
    if let Some(glint) = images
        .iter()
        .find(|image| image.texture.path == "textures/misc/enchanted_glint_item.png")
    {
        renderer.upload_item_glint_texture(
            glint.texture.size[0],
            glint.texture.size[1],
            &glint.rgba,
        )?;
    }
    tracing::info!(
        textures = images.len(),
        "loaded vanilla entity model textures"
    );
    Ok(())
}

fn load_entity_model_texture_images(roots: &PackRoots) -> Result<Vec<EntityModelTextureImage>> {
    entity_model_texture_refs()
        .iter()
        .copied()
        .map(|texture| load_entity_model_texture_image(roots, texture))
        .collect()
}

fn load_entity_model_texture_image(
    roots: &PackRoots,
    texture: EntityModelTextureRef,
) -> Result<EntityModelTextureImage> {
    let location = ResourceLocation::parse(texture.path)?;
    let resource = roots
        .resource_stack()
        .get_resource(&location)
        .with_context(|| format!("missing entity texture minecraft:{}", texture.path))?;
    let image = SpriteImage::from_png_file(entity_texture_id(texture.path), resource.path)?;
    if [image.width, image.height] != texture.size {
        bail!(
            "entity texture {} has {}x{}, expected {}x{}",
            texture.path,
            image.width,
            image.height,
            texture.size[0],
            texture.size[1]
        );
    }
    Ok(EntityModelTextureImage::new(texture, image.rgba))
}

fn entity_texture_id(path: &str) -> String {
    let path = path.strip_suffix(".png").unwrap_or(path);
    format!("minecraft:{path}")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn loads_vanilla_entity_textures_from_resource_stack() {
        let temp = unique_temp_dir("bbb-entity-textures");
        let sources = temp.join("sources").join("26.1");
        for texture in entity_model_texture_refs() {
            let texture_path = sources.join("assets").join("minecraft").join(texture.path);
            std::fs::create_dir_all(texture_path.parent().unwrap()).unwrap();
            write_png(&texture_path, texture.size[0], texture.size[1]);
        }
        let roots = PackRoots {
            mc_code_root: temp.clone(),
            sources_dir: sources,
            assets_dir: temp.join("unused-assets"),
            generated_assets_dir: None,
            resource_pack_dirs: Vec::new(),
        };

        let images = load_entity_model_texture_images(&roots).unwrap();

        assert_eq!(
            images
                .iter()
                .map(|image| image.texture.path)
                .collect::<Vec<_>>(),
            vec![
                "textures/entity/player/slim/alex.png",
                "textures/entity/player/slim/ari.png",
                "textures/entity/player/slim/efe.png",
                "textures/entity/player/slim/kai.png",
                "textures/entity/player/slim/makena.png",
                "textures/entity/player/slim/noor.png",
                "textures/entity/player/slim/steve.png",
                "textures/entity/player/slim/sunny.png",
                "textures/entity/player/slim/zuri.png",
                "textures/entity/player/wide/alex.png",
                "textures/entity/player/wide/ari.png",
                "textures/entity/player/wide/efe.png",
                "textures/entity/player/wide/kai.png",
                "textures/entity/player/wide/makena.png",
                "textures/entity/player/wide/noor.png",
                "textures/entity/player/wide/steve.png",
                "textures/entity/player/wide/sunny.png",
                "textures/entity/player/wide/zuri.png",
                "textures/entity/experience/experience_orb.png",
                "textures/entity/sheep/sheep.png",
                "textures/entity/sheep/sheep_baby.png",
                "textures/entity/sheep/sheep_wool_undercoat.png",
                "textures/entity/sheep/sheep_wool.png",
                "textures/entity/sheep/sheep_wool_baby.png",
                "textures/entity/wolf/wolf.png",
                "textures/entity/wolf/wolf_tame.png",
                "textures/entity/wolf/wolf_angry.png",
                "textures/entity/wolf/wolf_baby.png",
                "textures/entity/wolf/wolf_tame_baby.png",
                "textures/entity/wolf/wolf_angry_baby.png",
                "textures/entity/wolf/wolf_spotted.png",
                "textures/entity/wolf/wolf_spotted_tame.png",
                "textures/entity/wolf/wolf_spotted_angry.png",
                "textures/entity/wolf/wolf_spotted_baby.png",
                "textures/entity/wolf/wolf_spotted_tame_baby.png",
                "textures/entity/wolf/wolf_spotted_angry_baby.png",
                "textures/entity/wolf/wolf_snowy.png",
                "textures/entity/wolf/wolf_snowy_tame.png",
                "textures/entity/wolf/wolf_snowy_angry.png",
                "textures/entity/wolf/wolf_snowy_baby.png",
                "textures/entity/wolf/wolf_snowy_tame_baby.png",
                "textures/entity/wolf/wolf_snowy_angry_baby.png",
                "textures/entity/wolf/wolf_black.png",
                "textures/entity/wolf/wolf_black_tame.png",
                "textures/entity/wolf/wolf_black_angry.png",
                "textures/entity/wolf/wolf_black_baby.png",
                "textures/entity/wolf/wolf_black_tame_baby.png",
                "textures/entity/wolf/wolf_black_angry_baby.png",
                "textures/entity/wolf/wolf_ashen.png",
                "textures/entity/wolf/wolf_ashen_tame.png",
                "textures/entity/wolf/wolf_ashen_angry.png",
                "textures/entity/wolf/wolf_ashen_baby.png",
                "textures/entity/wolf/wolf_ashen_tame_baby.png",
                "textures/entity/wolf/wolf_ashen_angry_baby.png",
                "textures/entity/wolf/wolf_rusty.png",
                "textures/entity/wolf/wolf_rusty_tame.png",
                "textures/entity/wolf/wolf_rusty_angry.png",
                "textures/entity/wolf/wolf_rusty_baby.png",
                "textures/entity/wolf/wolf_rusty_tame_baby.png",
                "textures/entity/wolf/wolf_rusty_angry_baby.png",
                "textures/entity/wolf/wolf_woods.png",
                "textures/entity/wolf/wolf_woods_tame.png",
                "textures/entity/wolf/wolf_woods_angry.png",
                "textures/entity/wolf/wolf_woods_baby.png",
                "textures/entity/wolf/wolf_woods_tame_baby.png",
                "textures/entity/wolf/wolf_woods_angry_baby.png",
                "textures/entity/wolf/wolf_chestnut.png",
                "textures/entity/wolf/wolf_chestnut_tame.png",
                "textures/entity/wolf/wolf_chestnut_angry.png",
                "textures/entity/wolf/wolf_chestnut_baby.png",
                "textures/entity/wolf/wolf_chestnut_tame_baby.png",
                "textures/entity/wolf/wolf_chestnut_angry_baby.png",
                "textures/entity/wolf/wolf_striped.png",
                "textures/entity/wolf/wolf_striped_tame.png",
                "textures/entity/wolf/wolf_striped_angry.png",
                "textures/entity/wolf/wolf_striped_baby.png",
                "textures/entity/wolf/wolf_striped_tame_baby.png",
                "textures/entity/wolf/wolf_striped_angry_baby.png",
                "textures/entity/wolf/wolf_collar.png",
                "textures/entity/wolf/wolf_collar_baby.png",
                "textures/entity/equipment/wolf_body/armadillo_scute.png",
                "textures/entity/equipment/wolf_body/armadillo_scute_overlay.png",
                "textures/entity/wolf/wolf_armor_crackiness_low.png",
                "textures/entity/wolf/wolf_armor_crackiness_medium.png",
                "textures/entity/wolf/wolf_armor_crackiness_high.png",
                "textures/misc/enchanted_glint_armor.png",
                "textures/entity/goat/goat.png",
                "textures/entity/goat/goat_baby.png",
                "textures/entity/bear/polarbear.png",
                "textures/entity/bear/polarbear_baby.png",
                "textures/entity/hoglin/hoglin.png",
                "textures/entity/hoglin/hoglin_baby.png",
                "textures/entity/hoglin/zoglin.png",
                "textures/entity/hoglin/zoglin_baby.png",
                "textures/entity/illager/ravager.png",
                "textures/entity/villager/villager.png",
                "textures/entity/villager/villager_baby.png",
                "textures/entity/villager/type/desert.png",
                "textures/entity/villager/type/jungle.png",
                "textures/entity/villager/type/plains.png",
                "textures/entity/villager/type/savanna.png",
                "textures/entity/villager/type/snow.png",
                "textures/entity/villager/type/swamp.png",
                "textures/entity/villager/type/taiga.png",
                "textures/entity/villager/baby/desert.png",
                "textures/entity/villager/baby/jungle.png",
                "textures/entity/villager/baby/plains.png",
                "textures/entity/villager/baby/savanna.png",
                "textures/entity/villager/baby/snow.png",
                "textures/entity/villager/baby/swamp.png",
                "textures/entity/villager/baby/taiga.png",
                "textures/entity/villager/profession/armorer.png",
                "textures/entity/villager/profession/butcher.png",
                "textures/entity/villager/profession/cartographer.png",
                "textures/entity/villager/profession/cleric.png",
                "textures/entity/villager/profession/farmer.png",
                "textures/entity/villager/profession/fisherman.png",
                "textures/entity/villager/profession/fletcher.png",
                "textures/entity/villager/profession/leatherworker.png",
                "textures/entity/villager/profession/librarian.png",
                "textures/entity/villager/profession/mason.png",
                "textures/entity/villager/profession/nitwit.png",
                "textures/entity/villager/profession/shepherd.png",
                "textures/entity/villager/profession/toolsmith.png",
                "textures/entity/villager/profession/weaponsmith.png",
                "textures/entity/villager/profession_level/stone.png",
                "textures/entity/villager/profession_level/iron.png",
                "textures/entity/villager/profession_level/gold.png",
                "textures/entity/villager/profession_level/emerald.png",
                "textures/entity/villager/profession_level/diamond.png",
                "textures/entity/wandering_trader/wandering_trader.png",
                "textures/entity/chicken/chicken_temperate.png",
                "textures/entity/chicken/chicken_temperate_baby.png",
                "textures/entity/chicken/chicken_warm.png",
                "textures/entity/chicken/chicken_warm_baby.png",
                "textures/entity/chicken/chicken_cold.png",
                "textures/entity/chicken/chicken_cold_baby.png",
                "textures/entity/pig/pig_temperate.png",
                "textures/entity/pig/pig_temperate_baby.png",
                "textures/entity/pig/pig_warm.png",
                "textures/entity/pig/pig_warm_baby.png",
                "textures/entity/pig/pig_cold.png",
                "textures/entity/pig/pig_cold_baby.png",
                "textures/entity/equipment/pig_saddle/saddle.png",
                "textures/entity/cow/cow_temperate.png",
                "textures/entity/cow/cow_temperate_baby.png",
                "textures/entity/cow/cow_warm.png",
                "textures/entity/cow/cow_warm_baby.png",
                "textures/entity/cow/cow_cold.png",
                "textures/entity/cow/cow_cold_baby.png",
                "textures/entity/skeleton/skeleton.png",
                "textures/entity/skeleton/stray.png",
                "textures/entity/skeleton/stray_overlay.png",
                "textures/entity/skeleton/parched.png",
                "textures/entity/skeleton/wither_skeleton.png",
                "textures/entity/skeleton/bogged.png",
                "textures/entity/skeleton/bogged_overlay.png",
                "textures/entity/creeper/creeper.png",
                "textures/entity/creeper/creeper_armor.png",
                "textures/entity/spider/spider.png",
                "textures/entity/spider/cave_spider.png",
                "textures/entity/spider/spider_eyes.png",
                "textures/entity/enderman/enderman.png",
                "textures/entity/enderman/enderman_eyes.png",
                "textures/entity/copper_golem/copper_golem.png",
                "textures/entity/copper_golem/copper_golem_exposed.png",
                "textures/entity/copper_golem/copper_golem_weathered.png",
                "textures/entity/copper_golem/copper_golem_oxidized.png",
                "textures/entity/copper_golem/copper_golem_eyes.png",
                "textures/entity/copper_golem/copper_golem_eyes_exposed.png",
                "textures/entity/copper_golem/copper_golem_eyes_weathered.png",
                "textures/entity/copper_golem/copper_golem_eyes_oxidized.png",
                "textures/entity/iron_golem/iron_golem.png",
                "textures/entity/iron_golem/iron_golem_crackiness_low.png",
                "textures/entity/iron_golem/iron_golem_crackiness_medium.png",
                "textures/entity/iron_golem/iron_golem_crackiness_high.png",
                "textures/entity/snow_golem/snow_golem.png",
                "textures/entity/witch/witch.png",
                "textures/entity/slime/slime.png",
                "textures/entity/slime/magmacube.png",
                "textures/entity/ghast/ghast.png",
                "textures/entity/ghast/ghast_shooting.png",
                "textures/entity/blaze/blaze.png",
                "textures/entity/endermite/endermite.png",
                "textures/entity/silverfish/silverfish.png",
                "textures/entity/lead_knot/lead_knot.png",
                "textures/entity/trident/trident.png",
                "textures/entity/chest/normal.png",
                "textures/entity/chest/normal_left.png",
                "textures/entity/chest/normal_right.png",
                "textures/entity/chest/trapped.png",
                "textures/entity/chest/trapped_left.png",
                "textures/entity/chest/trapped_right.png",
                "textures/entity/chest/ender.png",
                "textures/entity/chest/copper.png",
                "textures/entity/chest/copper_left.png",
                "textures/entity/chest/copper_right.png",
                "textures/entity/chest/copper_exposed.png",
                "textures/entity/chest/copper_exposed_left.png",
                "textures/entity/chest/copper_exposed_right.png",
                "textures/entity/chest/copper_weathered.png",
                "textures/entity/chest/copper_weathered_left.png",
                "textures/entity/chest/copper_weathered_right.png",
                "textures/entity/chest/copper_oxidized.png",
                "textures/entity/chest/copper_oxidized_left.png",
                "textures/entity/chest/copper_oxidized_right.png",
                "textures/entity/signs/oak.png",
                "textures/entity/signs/spruce.png",
                "textures/entity/signs/birch.png",
                "textures/entity/signs/acacia.png",
                "textures/entity/signs/cherry.png",
                "textures/entity/signs/jungle.png",
                "textures/entity/signs/dark_oak.png",
                "textures/entity/signs/pale_oak.png",
                "textures/entity/signs/crimson.png",
                "textures/entity/signs/warped.png",
                "textures/entity/signs/mangrove.png",
                "textures/entity/signs/bamboo.png",
                "textures/entity/signs/hanging/oak.png",
                "textures/entity/signs/hanging/spruce.png",
                "textures/entity/signs/hanging/birch.png",
                "textures/entity/signs/hanging/acacia.png",
                "textures/entity/signs/hanging/cherry.png",
                "textures/entity/signs/hanging/jungle.png",
                "textures/entity/signs/hanging/dark_oak.png",
                "textures/entity/signs/hanging/pale_oak.png",
                "textures/entity/signs/hanging/crimson.png",
                "textures/entity/signs/hanging/warped.png",
                "textures/entity/signs/hanging/mangrove.png",
                "textures/entity/signs/hanging/bamboo.png",
                "textures/entity/bed/white.png",
                "textures/entity/bed/orange.png",
                "textures/entity/bed/magenta.png",
                "textures/entity/bed/light_blue.png",
                "textures/entity/bed/yellow.png",
                "textures/entity/bed/lime.png",
                "textures/entity/bed/pink.png",
                "textures/entity/bed/gray.png",
                "textures/entity/bed/light_gray.png",
                "textures/entity/bed/cyan.png",
                "textures/entity/bed/purple.png",
                "textures/entity/bed/blue.png",
                "textures/entity/bed/brown.png",
                "textures/entity/bed/green.png",
                "textures/entity/bed/red.png",
                "textures/entity/bed/black.png",
                "textures/entity/bell/bell_body.png",
                "textures/entity/decorated_pot/decorated_pot_base.png",
                "textures/entity/decorated_pot/decorated_pot_side.png",
                "textures/entity/decorated_pot/angler_pottery_pattern.png",
                "textures/entity/decorated_pot/archer_pottery_pattern.png",
                "textures/entity/decorated_pot/arms_up_pottery_pattern.png",
                "textures/entity/decorated_pot/blade_pottery_pattern.png",
                "textures/entity/decorated_pot/brewer_pottery_pattern.png",
                "textures/entity/decorated_pot/burn_pottery_pattern.png",
                "textures/entity/decorated_pot/danger_pottery_pattern.png",
                "textures/entity/decorated_pot/explorer_pottery_pattern.png",
                "textures/entity/decorated_pot/flow_pottery_pattern.png",
                "textures/entity/decorated_pot/friend_pottery_pattern.png",
                "textures/entity/decorated_pot/guster_pottery_pattern.png",
                "textures/entity/decorated_pot/heart_pottery_pattern.png",
                "textures/entity/decorated_pot/heartbreak_pottery_pattern.png",
                "textures/entity/decorated_pot/howl_pottery_pattern.png",
                "textures/entity/decorated_pot/miner_pottery_pattern.png",
                "textures/entity/decorated_pot/mourner_pottery_pattern.png",
                "textures/entity/decorated_pot/plenty_pottery_pattern.png",
                "textures/entity/decorated_pot/prize_pottery_pattern.png",
                "textures/entity/decorated_pot/scrape_pottery_pattern.png",
                "textures/entity/decorated_pot/sheaf_pottery_pattern.png",
                "textures/entity/decorated_pot/shelter_pottery_pattern.png",
                "textures/entity/decorated_pot/skull_pottery_pattern.png",
                "textures/entity/decorated_pot/snort_pottery_pattern.png",
                "textures/entity/trident/trident_riptide.png",
                "textures/misc/enchanted_glint_item.png",
                "textures/entity/illager/evoker_fangs.png",
                "textures/entity/tadpole/tadpole.png",
                "textures/entity/creaking/creaking.png",
                "textures/entity/creaking/creaking_eyes.png",
                "textures/entity/sniffer/sniffer.png",
                "textures/entity/sniffer/snifflet.png",
                "textures/entity/parrot/parrot_red_blue.png",
                "textures/entity/parrot/parrot_blue.png",
                "textures/entity/parrot/parrot_green.png",
                "textures/entity/parrot/parrot_yellow_blue.png",
                "textures/entity/parrot/parrot_grey.png",
                "textures/entity/shulker/shulker.png",
                "textures/entity/shulker/shulker_white.png",
                "textures/entity/shulker/shulker_orange.png",
                "textures/entity/shulker/shulker_magenta.png",
                "textures/entity/shulker/shulker_light_blue.png",
                "textures/entity/shulker/shulker_yellow.png",
                "textures/entity/shulker/shulker_lime.png",
                "textures/entity/shulker/shulker_pink.png",
                "textures/entity/shulker/shulker_gray.png",
                "textures/entity/shulker/shulker_light_gray.png",
                "textures/entity/shulker/shulker_cyan.png",
                "textures/entity/shulker/shulker_purple.png",
                "textures/entity/shulker/shulker_blue.png",
                "textures/entity/shulker/shulker_brown.png",
                "textures/entity/shulker/shulker_green.png",
                "textures/entity/shulker/shulker_red.png",
                "textures/entity/shulker/shulker_black.png",
                "textures/entity/enderdragon/dragon.png",
                "textures/entity/enderdragon/dragon_exploding.png",
                "textures/entity/enderdragon/dragon_eyes.png",
                "textures/entity/nautilus/nautilus.png",
                "textures/entity/nautilus/nautilus_baby.png",
                "textures/entity/equipment/nautilus_saddle/saddle.png",
                "textures/entity/equipment/nautilus_body/copper.png",
                "textures/entity/equipment/nautilus_body/iron.png",
                "textures/entity/equipment/nautilus_body/gold.png",
                "textures/entity/equipment/nautilus_body/diamond.png",
                "textures/entity/equipment/nautilus_body/netherite.png",
                "textures/entity/nautilus/zombie_nautilus.png",
                "textures/entity/nautilus/zombie_nautilus_coral.png",
                "textures/entity/panda/panda.png",
                "textures/entity/panda/panda_baby.png",
                "textures/entity/panda/panda_lazy.png",
                "textures/entity/panda/lazy_panda_baby.png",
                "textures/entity/panda/panda_worried.png",
                "textures/entity/panda/worried_panda_baby.png",
                "textures/entity/panda/panda_playful.png",
                "textures/entity/panda/playful_panda_baby.png",
                "textures/entity/panda/panda_brown.png",
                "textures/entity/panda/brown_panda_baby.png",
                "textures/entity/panda/panda_weak.png",
                "textures/entity/panda/weak_panda_baby.png",
                "textures/entity/panda/panda_aggressive.png",
                "textures/entity/panda/aggressive_panda_baby.png",
                "textures/entity/axolotl/axolotl_lucy.png",
                "textures/entity/axolotl/axolotl_lucy_baby.png",
                "textures/entity/axolotl/axolotl_wild.png",
                "textures/entity/axolotl/axolotl_wild_baby.png",
                "textures/entity/axolotl/axolotl_gold.png",
                "textures/entity/axolotl/axolotl_gold_baby.png",
                "textures/entity/axolotl/axolotl_cyan.png",
                "textures/entity/axolotl/axolotl_cyan_baby.png",
                "textures/entity/axolotl/axolotl_blue.png",
                "textures/entity/axolotl/axolotl_blue_baby.png",
                "textures/entity/fox/fox.png",
                "textures/entity/fox/fox_baby.png",
                "textures/entity/fox/fox_sleep.png",
                "textures/entity/fox/fox_sleep_baby.png",
                "textures/entity/fox/fox_snow.png",
                "textures/entity/fox/fox_snow_baby.png",
                "textures/entity/fox/fox_snow_sleep.png",
                "textures/entity/fox/fox_snow_sleep_baby.png",
                "textures/entity/rabbit/rabbit_brown.png",
                "textures/entity/rabbit/rabbit_brown_baby.png",
                "textures/entity/rabbit/rabbit_white.png",
                "textures/entity/rabbit/rabbit_white_baby.png",
                "textures/entity/rabbit/rabbit_black.png",
                "textures/entity/rabbit/rabbit_black_baby.png",
                "textures/entity/rabbit/rabbit_white_splotched.png",
                "textures/entity/rabbit/rabbit_white_splotched_baby.png",
                "textures/entity/rabbit/rabbit_gold.png",
                "textures/entity/rabbit/rabbit_gold_baby.png",
                "textures/entity/rabbit/rabbit_salt.png",
                "textures/entity/rabbit/rabbit_salt_baby.png",
                "textures/entity/rabbit/rabbit_caerbannog.png",
                "textures/entity/rabbit/rabbit_caerbannog_baby.png",
                "textures/entity/rabbit/rabbit_toast.png",
                "textures/entity/rabbit/rabbit_toast_baby.png",
                "textures/entity/cat/cat_tabby.png",
                "textures/entity/cat/cat_tabby_baby.png",
                "textures/entity/cat/cat_black.png",
                "textures/entity/cat/cat_black_baby.png",
                "textures/entity/cat/cat_red.png",
                "textures/entity/cat/cat_red_baby.png",
                "textures/entity/cat/cat_siamese.png",
                "textures/entity/cat/cat_siamese_baby.png",
                "textures/entity/cat/cat_british_shorthair.png",
                "textures/entity/cat/cat_british_shorthair_baby.png",
                "textures/entity/cat/cat_calico.png",
                "textures/entity/cat/cat_calico_baby.png",
                "textures/entity/cat/cat_persian.png",
                "textures/entity/cat/cat_persian_baby.png",
                "textures/entity/cat/cat_ragdoll.png",
                "textures/entity/cat/cat_ragdoll_baby.png",
                "textures/entity/cat/cat_white.png",
                "textures/entity/cat/cat_white_baby.png",
                "textures/entity/cat/cat_jellie.png",
                "textures/entity/cat/cat_jellie_baby.png",
                "textures/entity/cat/cat_all_black.png",
                "textures/entity/cat/cat_all_black_baby.png",
                "textures/entity/cat/ocelot.png",
                "textures/entity/cat/ocelot_baby.png",
                "textures/entity/cat/cat_collar.png",
                "textures/entity/cat/cat_collar_baby.png",
                "textures/entity/cow/mooshroom_red.png",
                "textures/entity/cow/mooshroom_red_baby.png",
                "textures/entity/cow/mooshroom_brown.png",
                "textures/entity/cow/mooshroom_brown_baby.png",
                "textures/entity/end_crystal/end_crystal.png",
                "textures/entity/end_crystal/end_crystal_beam.png",
                "textures/entity/projectiles/arrow.png",
                "textures/entity/projectiles/arrow_tipped.png",
                "textures/entity/projectiles/arrow_spectral.png",
                "textures/entity/llama/llama_spit.png",
                "textures/entity/shulker/spark.png",
                "textures/entity/wither/wither.png",
                "textures/entity/wither/wither_invulnerable.png",
                "textures/entity/wither/wither_armor.png",
                "textures/entity/projectiles/wind_charge.png",
                "textures/entity/guardian/guardian.png",
                "textures/entity/guardian/guardian_elder.png",
                "textures/entity/guardian/guardian_beam.png",
                "textures/entity/warden/warden.png",
                "textures/entity/warden/warden_bioluminescent_layer.png",
                "textures/entity/warden/warden_pulsating_spots_1.png",
                "textures/entity/warden/warden_pulsating_spots_2.png",
                "textures/entity/warden/warden_heart.png",
                "textures/entity/frog/frog_temperate.png",
                "textures/entity/frog/frog_warm.png",
                "textures/entity/frog/frog_cold.png",
                "textures/entity/armadillo/armadillo.png",
                "textures/entity/armadillo/armadillo_baby.png",
                "textures/entity/phantom/phantom.png",
                "textures/entity/phantom/phantom_eyes.png",
                "textures/entity/fish/pufferfish.png",
                "textures/entity/ghast/happy_ghast.png",
                "textures/entity/minecart/minecart.png",
                "textures/entity/armorstand/armorstand.png",
                "textures/entity/zombie/zombie.png",
                "textures/entity/zombie/zombie_baby.png",
                "textures/entity/zombie/husk.png",
                "textures/entity/zombie/husk_baby.png",
                "textures/entity/zombie/drowned.png",
                "textures/entity/zombie/drowned_baby.png",
                "textures/entity/zombie/drowned_outer_layer.png",
                "textures/entity/zombie/drowned_outer_layer_baby.png",
                "textures/entity/zombie_villager/zombie_villager.png",
                "textures/entity/zombie_villager/zombie_villager_baby.png",
                "textures/entity/zombie_villager/type/desert.png",
                "textures/entity/zombie_villager/type/jungle.png",
                "textures/entity/zombie_villager/type/plains.png",
                "textures/entity/zombie_villager/type/savanna.png",
                "textures/entity/zombie_villager/type/snow.png",
                "textures/entity/zombie_villager/type/swamp.png",
                "textures/entity/zombie_villager/type/taiga.png",
                "textures/entity/zombie_villager/baby/desert.png",
                "textures/entity/zombie_villager/baby/jungle.png",
                "textures/entity/zombie_villager/baby/plains.png",
                "textures/entity/zombie_villager/baby/savanna.png",
                "textures/entity/zombie_villager/baby/snow.png",
                "textures/entity/zombie_villager/baby/swamp.png",
                "textures/entity/zombie_villager/baby/taiga.png",
                "textures/entity/zombie_villager/profession/armorer.png",
                "textures/entity/zombie_villager/profession/butcher.png",
                "textures/entity/zombie_villager/profession/cartographer.png",
                "textures/entity/zombie_villager/profession/cleric.png",
                "textures/entity/zombie_villager/profession/farmer.png",
                "textures/entity/zombie_villager/profession/fisherman.png",
                "textures/entity/zombie_villager/profession/fletcher.png",
                "textures/entity/zombie_villager/profession/leatherworker.png",
                "textures/entity/zombie_villager/profession/librarian.png",
                "textures/entity/zombie_villager/profession/mason.png",
                "textures/entity/zombie_villager/profession/nitwit.png",
                "textures/entity/zombie_villager/profession/shepherd.png",
                "textures/entity/zombie_villager/profession/toolsmith.png",
                "textures/entity/zombie_villager/profession/weaponsmith.png",
                "textures/entity/zombie_villager/profession_level/stone.png",
                "textures/entity/zombie_villager/profession_level/iron.png",
                "textures/entity/zombie_villager/profession_level/gold.png",
                "textures/entity/zombie_villager/profession_level/emerald.png",
                "textures/entity/zombie_villager/profession_level/diamond.png",
                "textures/entity/piglin/piglin.png",
                "textures/entity/piglin/piglin_baby.png",
                "textures/entity/piglin/piglin_brute.png",
                "textures/entity/piglin/zombified_piglin.png",
                "textures/entity/piglin/zombified_piglin_baby.png",
                "textures/entity/illager/evoker.png",
                "textures/entity/illager/illusioner.png",
                "textures/entity/illager/pillager.png",
                "textures/entity/illager/vindicator.png",
                "textures/entity/boat/acacia.png",
                "textures/entity/chest_boat/acacia.png",
                "textures/entity/boat/bamboo.png",
                "textures/entity/chest_boat/bamboo.png",
                "textures/entity/boat/birch.png",
                "textures/entity/chest_boat/birch.png",
                "textures/entity/boat/cherry.png",
                "textures/entity/chest_boat/cherry.png",
                "textures/entity/boat/dark_oak.png",
                "textures/entity/chest_boat/dark_oak.png",
                "textures/entity/boat/jungle.png",
                "textures/entity/chest_boat/jungle.png",
                "textures/entity/boat/mangrove.png",
                "textures/entity/chest_boat/mangrove.png",
                "textures/entity/boat/oak.png",
                "textures/entity/chest_boat/oak.png",
                "textures/entity/boat/pale_oak.png",
                "textures/entity/chest_boat/pale_oak.png",
                "textures/entity/boat/spruce.png",
                "textures/entity/chest_boat/spruce.png",
                "textures/entity/horse/horse_white.png",
                "textures/entity/horse/horse_white_baby.png",
                "textures/entity/horse/horse_creamy.png",
                "textures/entity/horse/horse_creamy_baby.png",
                "textures/entity/horse/horse_chestnut.png",
                "textures/entity/horse/horse_chestnut_baby.png",
                "textures/entity/horse/horse_brown.png",
                "textures/entity/horse/horse_brown_baby.png",
                "textures/entity/horse/horse_black.png",
                "textures/entity/horse/horse_black_baby.png",
                "textures/entity/horse/horse_gray.png",
                "textures/entity/horse/horse_gray_baby.png",
                "textures/entity/horse/horse_darkbrown.png",
                "textures/entity/horse/horse_darkbrown_baby.png",
                "textures/entity/horse/horse_markings_white.png",
                "textures/entity/horse/horse_markings_white_baby.png",
                "textures/entity/horse/horse_markings_whitefield.png",
                "textures/entity/horse/horse_markings_whitefield_baby.png",
                "textures/entity/horse/horse_markings_whitedots.png",
                "textures/entity/horse/horse_markings_whitedots_baby.png",
                "textures/entity/horse/horse_markings_blackdots.png",
                "textures/entity/horse/horse_markings_blackdots_baby.png",
                "textures/entity/horse/horse_skeleton.png",
                "textures/entity/horse/horse_skeleton_baby.png",
                "textures/entity/horse/horse_zombie.png",
                "textures/entity/horse/horse_zombie_baby.png",
                "textures/entity/horse/donkey.png",
                "textures/entity/horse/donkey_baby.png",
                "textures/entity/horse/mule.png",
                "textures/entity/horse/mule_baby.png",
                "textures/entity/equipment/horse_saddle/saddle.png",
                "textures/entity/equipment/donkey_saddle/saddle.png",
                "textures/entity/equipment/mule_saddle/saddle.png",
                "textures/entity/equipment/skeleton_horse_saddle/saddle.png",
                "textures/entity/equipment/zombie_horse_saddle/saddle.png",
                "textures/entity/equipment/horse_body/leather.png",
                "textures/entity/equipment/horse_body/leather_overlay.png",
                "textures/entity/equipment/horse_body/copper.png",
                "textures/entity/equipment/horse_body/iron.png",
                "textures/entity/equipment/horse_body/gold.png",
                "textures/entity/equipment/horse_body/diamond.png",
                "textures/entity/equipment/horse_body/netherite.png",
                "textures/entity/llama/llama_creamy.png",
                "textures/entity/llama/llama_creamy_baby.png",
                "textures/entity/llama/llama_white.png",
                "textures/entity/llama/llama_white_baby.png",
                "textures/entity/llama/llama_brown.png",
                "textures/entity/llama/llama_brown_baby.png",
                "textures/entity/llama/llama_gray.png",
                "textures/entity/llama/llama_gray_baby.png",
                "textures/entity/equipment/llama_body/white.png",
                "textures/entity/equipment/llama_body/orange.png",
                "textures/entity/equipment/llama_body/magenta.png",
                "textures/entity/equipment/llama_body/light_blue.png",
                "textures/entity/equipment/llama_body/yellow.png",
                "textures/entity/equipment/llama_body/lime.png",
                "textures/entity/equipment/llama_body/pink.png",
                "textures/entity/equipment/llama_body/gray.png",
                "textures/entity/equipment/llama_body/light_gray.png",
                "textures/entity/equipment/llama_body/cyan.png",
                "textures/entity/equipment/llama_body/purple.png",
                "textures/entity/equipment/llama_body/blue.png",
                "textures/entity/equipment/llama_body/brown.png",
                "textures/entity/equipment/llama_body/green.png",
                "textures/entity/equipment/llama_body/red.png",
                "textures/entity/equipment/llama_body/black.png",
                "textures/entity/equipment/llama_body/trader_llama.png",
                "textures/entity/equipment/llama_body/trader_llama_baby.png",
                "textures/entity/camel/camel.png",
                "textures/entity/camel/camel_baby.png",
                "textures/entity/camel/camel_husk.png",
                "textures/entity/equipment/camel_saddle/saddle.png",
                "textures/entity/equipment/camel_husk_saddle/saddle.png",
                "textures/entity/squid/squid.png",
                "textures/entity/squid/squid_baby.png",
                "textures/entity/squid/glow_squid.png",
                "textures/entity/squid/glow_squid_baby.png",
                "textures/entity/fish/cod.png",
                "textures/entity/fish/salmon.png",
                "textures/entity/fish/tropical_a.png",
                "textures/entity/fish/tropical_b.png",
                "textures/entity/illager/vex.png",
                "textures/entity/illager/vex_charging.png",
                "textures/entity/allay/allay.png",
                "textures/entity/strider/strider.png",
                "textures/entity/strider/strider_baby.png",
                "textures/entity/strider/strider_cold.png",
                "textures/entity/strider/strider_cold_baby.png",
                "textures/entity/equipment/strider_saddle/saddle.png",
                "textures/entity/turtle/turtle.png",
                "textures/entity/turtle/turtle_baby.png",
                "textures/entity/bat/bat.png",
                "textures/entity/bee/bee.png",
                "textures/entity/bee/bee_baby.png",
                "textures/entity/bee/bee_angry.png",
                "textures/entity/bee/bee_nectar.png",
                "textures/entity/bee/bee_angry_nectar.png",
                "textures/entity/bee/bee_angry_baby.png",
                "textures/entity/bee/bee_nectar_baby.png",
                "textures/entity/bee/bee_angry_nectar_baby.png",
                "textures/entity/breeze/breeze.png",
                "textures/entity/breeze/breeze_eyes.png",
                "textures/entity/breeze/breeze_wind.png",
                "textures/entity/dolphin/dolphin.png",
                "textures/entity/dolphin/dolphin_baby.png",
                "textures/entity/fish/tropical_a_pattern_1.png",
                "textures/entity/fish/tropical_a_pattern_2.png",
                "textures/entity/fish/tropical_a_pattern_3.png",
                "textures/entity/fish/tropical_a_pattern_4.png",
                "textures/entity/fish/tropical_a_pattern_5.png",
                "textures/entity/fish/tropical_a_pattern_6.png",
                "textures/entity/fish/tropical_b_pattern_1.png",
                "textures/entity/fish/tropical_b_pattern_2.png",
                "textures/entity/fish/tropical_b_pattern_3.png",
                "textures/entity/fish/tropical_b_pattern_4.png",
                "textures/entity/fish/tropical_b_pattern_5.png",
                "textures/entity/fish/tropical_b_pattern_6.png",
                "textures/entity/equipment/humanoid/leather.png",
                "textures/entity/equipment/humanoid/copper.png",
                "textures/entity/equipment/humanoid/chainmail.png",
                "textures/entity/equipment/humanoid/iron.png",
                "textures/entity/equipment/humanoid/gold.png",
                "textures/entity/equipment/humanoid/diamond.png",
                "textures/entity/equipment/humanoid/turtle_scute.png",
                "textures/entity/equipment/humanoid/netherite.png",
                "textures/entity/equipment/humanoid_leggings/leather.png",
                "textures/entity/equipment/humanoid_leggings/copper.png",
                "textures/entity/equipment/humanoid_leggings/chainmail.png",
                "textures/entity/equipment/humanoid_leggings/iron.png",
                "textures/entity/equipment/humanoid_leggings/gold.png",
                "textures/entity/equipment/humanoid_leggings/diamond.png",
                "textures/entity/equipment/humanoid_leggings/netherite.png",
                "textures/entity/equipment/humanoid_baby/leather.png",
                "textures/entity/equipment/humanoid_baby/copper.png",
                "textures/entity/equipment/humanoid_baby/chainmail.png",
                "textures/entity/equipment/humanoid_baby/iron.png",
                "textures/entity/equipment/humanoid_baby/gold.png",
                "textures/entity/equipment/humanoid_baby/diamond.png",
                "textures/entity/equipment/humanoid_baby/turtle_scute.png",
                "textures/entity/equipment/humanoid_baby/netherite.png",
                "textures/entity/equipment/wings/elytra.png",
            ]
        );
        for image in images {
            assert_eq!(
                image.rgba.len(),
                usize::try_from(image.texture.size[0] * image.texture.size[1] * 4).unwrap()
            );
        }

        std::fs::remove_dir_all(temp).unwrap();
    }

    #[test]
    fn rejects_entity_texture_with_wrong_dimensions() {
        let temp = unique_temp_dir("bbb-entity-textures-bad");
        let sources = temp.join("sources").join("26.1");
        for texture in entity_model_texture_refs() {
            let texture_path = sources.join("assets").join("minecraft").join(texture.path);
            std::fs::create_dir_all(texture_path.parent().unwrap()).unwrap();
            let [width, height] = if texture.path == "textures/entity/sheep/sheep.png" {
                [32, 32]
            } else {
                texture.size
            };
            write_png(&texture_path, width, height);
        }
        let roots = PackRoots {
            mc_code_root: temp.clone(),
            sources_dir: sources,
            assets_dir: temp.join("unused-assets"),
            generated_assets_dir: None,
            resource_pack_dirs: Vec::new(),
        };

        let err = load_entity_model_texture_images(&roots).unwrap_err();

        assert!(err.to_string().contains("expected 64x32"));
        std::fs::remove_dir_all(temp).unwrap();
    }

    fn unique_temp_dir(prefix: &str) -> std::path::PathBuf {
        let nanos = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        std::env::temp_dir().join(format!("{prefix}-{}-{nanos}", std::process::id()))
    }

    fn write_png(path: &std::path::Path, width: u32, height: u32) {
        let image = image::RgbaImage::from_pixel(width, height, image::Rgba([7, 11, 13, 255]));
        image.save(path).unwrap();
    }
}
